language: php

php:
  - 7.1

install:
  # Speed up installing dependencies
  - composer global require hirak/prestissimo
  - composer install --prefer-source --no-interaction

before_script:
  # Take the travis-ci env var and put it in our configuration locally
  - sed -ri "s/COVERALLS_TOKEN/$COVERALLS_TOKEN/" .coveralls.yml
  - cat .coveralls.yml

  # Gets coveralls working in Travis-CI - see https://github.com/satooshi/php-coveralls/issues/61#issuecomment-166434043
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  # Push clover report to coveralls
  - travis_retry php vendor/bin/coveralls -v